### ISSUE TITLE
LINK DIE

### ISSUE THREAD

**Issue by saiquaan5** [Zenfection/Course#6]
Da em chao anh. 
Em hien dang xem cac video cua anh nhung hien tai link da die het. Anh kiem tra dum em vs a. Em cam on a

**Comment by Hecker-Chuoi** [comment]
Toàn bộ video đã bị die hết rồi anh ạ, mong anh kiểm tra dùm em với ạ, em cảm ơn anh nhiều.

**Comment by Zenfection1412** [comment]
Sẽ lên các video chất lượng hơn, tuy nhiên sẽ không thể public một thời gian hợp ly và cách public hợp lý
