### ISSUE TITLE
Link die

### ISSUE THREAD

**Issue by Hecker-Chuoi** [Zenfection/Course#7]
Em chào anh ạ, hiện tại thì em vừa mới vào đại học, trước đó nhờ có những video về ctdl và gt trên trang của anh mà em cũng có thể tự học để đi thi hsg tin. Hiện tại em vào để tự học lập trình web thì tất cả link đều đã die ạ. Mong rằng anh sẽ có thể khắc phục để giúp chúng em với ạ, có gì bọn em gửi anh ly cà phê ạ, em cảm ơn anh nhiều.

**Comment by Zenfection1412** [comment]
Sẽ lên các video chất lượng hơn, tuy nhiên sẽ không thể public một thời gian hợp ly và cách public hợp lý
